# =============================================================================
# 00-namespace.yaml
# Creates all required namespaces
# =============================================================================

---
apiVersion: v1
kind: Namespace
metadata:
  name: vault
  labels:
    name: vault

---
apiVersion: v1
kind: Namespace
metadata:
  name: itssolutions-db
  labels:
    name: itssolutions-db

---
apiVersion: v1
kind: Namespace
metadata:
  name: itssolutions-prod
  labels:
    name: itssolutions-prod
